cron: false

is_backtest: false
data_dir: "data"
db_dir: "storage"
stocks_file: "./storage/stocks.csv"
# end_data为 1997-09-24 代表None
end_date: "1997-09-24"
token: "3b5f8068af3f13161e7518dbd681e7f4e795209fd20b686ee0336946"

push:
  enable: false
  url: "https://example.com:5378/api/send_message"
  admin: "admin@example.com"
  admin_pass: "password"
  user: "user@example.com"
